config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      database: NCBizModuleDBTest2
      driver: ODBC Driver 17 for SQL Server
      password: Sa123456
      port: 1433
      schema: 'MyTest'
      server: localhost
      threads: 8
      type: sqlserver
      user: sa
  target: prod
